[package]
name = "infrastructure"
version = "0.1.0"
edition = "2018"

[dependencies.rocket]
version = "0.5.1"
features = ["json"]

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_postgres"]
