apiVersion: v1
kind: Service
metadata:
  name: striide-frontend
spec:
  selector:
    app: striide-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # This is the container port exposed by your frontend
  type: ClusterIP  # This will expose the service inside the cluster only
