[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
# internal dependencies
models = { path = "../models" }
# external dependencies
serde_json = "1.0.118"

[dependencies.rocket]
version = "0.5.1"
features = ["json"]
